### ISSUE TITLE
Option to use spago lockfile

### ISSUE THREAD

**Issue by thomashoneyman** [jeslie0/mkSpagoDerivation#1]
Spago has support for lockfiles if the spago.yaml config file has `lock: true` set. This can be used to fetch dependencies without needing the registry, and to fetch dependencies that aren't included in the registry (such as a fork of a package).

I've implemented this in purescript-overlay as seen here:
https://github.com/thomashoneyman/purescript-overlay/blob/main/nix/build-spago-lock.nix

with this helper:
https://github.com/thomashoneyman/purescript-overlay/blob/main/nix/build-spago-package.nix

There is also a pure-Nix fromYAML parser:
https://github.com/thomashoneyman/purescript-overlay/blob/main/nix/from-yaml.nix

Here's an example of its use:
https://github.com/thomashoneyman/purescript-overlay/blob/main/nix/examples/simple-ffi/default.nix

Thought you may find these links useful in this project — feel free to use any of it that seems useful to you! I'm glad to see another option for building projects with spago-next.

**Comment by jeslie0** [comment]
Thank you for the references! I will integrate lock file usage into the repository at some point in the future!

**Comment by jeslie0** [comment]
I have added functionality to use spago.lock files to build the .spago directory. I have tested it for registry and git packages, but I haven't been able to test it for local packages. When I find some example projects, I will be able to test out that functionality.

**Comment by jeslie0** [comment]
I am happy to close this now. I have converted this project into being based off a `spago.lock` file, which seems like a better idea than trying to regenerate the dependency tree in nix.
