### ISSUE TITLE
spago.lock format changed to JSON

### ISSUE THREAD

**Issue by jamesdbrock** [jeslie0/mkSpagoDerivation#3]
https://github.com/jeslie0/mkSpagoDerivation/blob/beeac0abd28514fc5b4c55d5e5e8e5d75adf7eaf/nix/buildFromLockFile.nix#L5

https://github.com/purescript/spago/pull/1280

**Comment by jamesdbrock** [comment]
Fabrizio said on the Discord today that “the format for the `spago.lock` is likely to change one more time before we call it stable.”

**Comment by jamesdbrock** [comment]
This looks like a really nice project @jeslie0 , good work.

**Comment by jeslie0** [comment]
Okay, I am happy to say that this has been done. I decided against keeping support for the YAML based lock files as Spago seems to change all lock files to JSON whenever it is invoked now.

**Comment by jamesdbrock** [comment]
Sweet, thanks man.
