### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by jamesdbrock** [jeslie0/mkSpagoDerivation#5]
My notes from using `mkSpagoDerivation`:

Needed in `flake.nix`:
```nix
  nixConfig.sandbox = "relaxed";
```

Needed in `~/.config/nix.conf`
```nix
experimental-features = nix-command flakes configurable-impure-env auto-allocate-uids
```

**Comment by jeslie0** [comment]
I would be interested to see your example flake that requires having sandbox set to relaxed. I've not needed that when I've used this in my projects. I also only have  `nix-command` and `flakes` enabled as experimental features. 

I'm not sure what is causing you to have to add these settings. If we can figure it out, I will update the documentation to make it clearer.

**Comment by jamesdbrock** [comment]
It is totally possible that I did something wrong and didn't really need those settings. I will post here if I figure it out.

**Comment by jamesdbrock** [comment]
Anyway, whatever weird thing I'm doing, `mkSpagoDerivation` is working perfectly for me, so thank you.

**Comment by jamesdbrock** [comment]
I'm working on this PR, if you're really curious. https://github.com/rowtype-yoga/purescript-protobuf/pull/40

**Comment by jeslie0** [comment]
I am starting to use purescript-protobuf in a personal project. It seems like maybe that is where you were getting the sandbox issues - I am also getting them when trying to build `protoc-gen-purescript`.

**Comment by jamesdbrock** [comment]
> I am starting to use purescript-protobuf in a personal project. 

Oh I'll finish that PR then. I think I can get it merged today.

**Comment by jamesdbrock** [comment]
@jeslie0  I tagged *protobuf* v4.5.0 but I can't publish it to the Registry yet. I think you can use v4.5.0 this way: https://github.com/rowtype-yoga/purescript-protobuf/issues/43

**Comment by jeslie0** [comment]
Thank you very much, I will try using the upgraded version when I'm back from work. 

I know this is the wrong place to ask this, but if you aren't using spago2nix anymore, do you still need the relaxed sandbox option in the flake? Removing that makes it much easier to build the plugin.

**Comment by jamesdbrock** [comment]
>  if you aren't using spago2nix anymore, do you still need the relaxed sandbox option in the flake? Removing that makes it much easier to build the plugin.

Good question. I just removed the relaxed sandbox and everything still works, so I pushed it to master.

**Comment by jamesdbrock** [comment]
And furthermore I don't seem to need this anymore either.
```
experimental-features = configurable-impure-env auto-allocate-uids
```
I don't know what that was about. Maybe I'll find out when I `nix-collect-garbage` and need to rebuild all this stuff.

**Comment by jeslie0** [comment]
Very happy, thank you! I added the new version to my [project](https://github.com/jeslie0/HaskellHomeLink/blob/1d17a908feb32b99a2c2b8d8838d948b16a87523/software/web/spago.yaml#L57). Happy to close this issue?

**Comment by jamesdbrock** [comment]
Thank you!
